name: ci-for-wallet
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: fetch code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: run lint
        run: |
          npm ci
          npm run lint
  unit-testing:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: fetch code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: unittesting
        run: |
          npm ci
          npm run test
